;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        compile
        cua--prefix-override-handler
        cua-exchange-point-and-mark
        end-of-buffer
        indent-for-tab-command
        move-text-up
        smex
        suspend-frame
        lsp-mode
        ))

(setq mc/cmds-to-run-once
      '(
        complete
        rectangle-left-char
        ))
